name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy to Raspberry Pi'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
          
      - run: cp requirements.txt src

      - name: Rsync to Raspberry Pi
        uses: oktupol/rsync-onion@v0.2
        with:
          source_dir: ./src/
          destination_dir: /home/pi/discord-pizzabot
          ssh_user: pi
          ssh_privatekey: ${{ secrets.SSH_PRIVATEKEY }}
          ssh_host_fingerprint: ${{ secrets.SSH_HOST_FINGERPRINT }}
          onion_host: ${{ secrets.ONION_HOST }}
          onion_client_auth_privatekey: ${{ secrets.ONION_CLIENT_AUTH_PRIVATEKEY }}
          delete: true
            
          before_rsync_command: |
            sudo systemctl stop discord-pizzabot.service
          
          after_rsync_command: |
            pip3 install -r /home/pi/discord-pizzabot/requirements.txt
            [ "$(systemctl is-enabled discord-pizzabot.service)" = "enabled" ] && sudo systemctl start discord-pizzabot.service